/**
 * Quick Wins Carbon Reduction Data
 * ─────────────────────────────────
 * Structured tip data for the Quick Wins carousel component.
 *
 * To add a new tip:
 * 1. Add a new object to the QUICK_WINS_DATA array below.
 * 2. Set `category` to one of: "small-habit" | "big-impact" | "india-specific"
 * 3. All fields are required — see the QuickWinTip type for schema.
 * 4. The component auto-discovers new entries and updates filter counts.
 */

export type QuickWinCategory = "small-habit" | "big-impact" | "india-specific";

export interface QuickWinTip {
  id: string;
  category: QuickWinCategory;
  icon: string;
  iconLabel: string;
  title: string;
  shortDescription: string;
  monthlySavings: number;
  whyItMatters: string;
  howTo: string[];
  indiaContext: string;
  sourceName: string;
  sourceUrl: string;
}

export const CATEGORY_META: Record<QuickWinCategory, { label: string; color: string; bgLight: string; bgDark: string }> = {
  "small-habit": {
    label: "Small Habit",
    color: "#52B788",
    bgLight: "bg-emerald-50 text-emerald-700 dark:bg-emerald-900/25 dark:text-emerald-300",
    bgDark: "bg-emerald-700",
  },
  "big-impact": {
    label: "Big Impact",
    color: "#F59E0B",
    bgLight: "bg-amber-50 text-amber-700 dark:bg-amber-900/25 dark:text-amber-300",
    bgDark: "bg-amber-600",
  },
  "india-specific": {
    label: "India-Specific",
    color: "#6366F1",
    bgLight: "bg-indigo-50 text-indigo-700 dark:bg-indigo-900/25 dark:text-indigo-300",
    bgDark: "bg-indigo-600",
  },
};

export const QUICK_WINS_DATA: QuickWinTip[] = [
  // ── SMALL HABIT ──
  {
    id: "metro-3x",
    category: "small-habit",
    icon: "🚆",
    iconLabel: "Train",
    title: "Switch to Metro 3x/Week",
    shortDescription: "Haridwar–Dehradun commuters can combine rail, bus, and e-rickshaw connections instead of driving the entire route.",
    monthlySavings: 8.4,
    whyItMatters: "Metro systems and electric public transport move large numbers of passengers efficiently, significantly lowering emissions per passenger-kilometre compared to private vehicles.",
    howTo: [
      "Use metro/rail for 3 weekly commutes",
      "Combine with e-rickshaws for first/last-mile travel",
      "Use digital route planners for optimal connections",
    ],
    indiaContext: "Delhi Metro and other electric transit systems offer lower-carbon mobility. Combining Indian Railways, Roadways buses, and e-rickshaws is practical for many Uttarakhand commuters.",
    sourceName: "Delhi Metro Rail Corporation",
    sourceUrl: "https://www.delhimetrorail.com",
  },
  {
    id: "delivery-2x-less",
    category: "small-habit",
    icon: "🍽",
    iconLabel: "Plate",
    title: "Order Delivery 2x Less per Week",
    shortDescription: "Pickup or home cooking cuts delivery distance and packaging waste.",
    monthlySavings: 3.2,
    whyItMatters: "Food delivery contributes emissions through transportation and single-use packaging.",
    howTo: [
      "Batch meal orders into fewer deliveries",
      "Cook at home more often",
      "Pick up nearby orders when possible",
    ],
    indiaContext: "Reducing frequent delivery usage in dense urban areas lowers both vehicle travel and packaging waste.",
    sourceName: "FSSAI",
    sourceUrl: "https://www.fssai.gov.in",
  },
  {
    id: "cloth-bag",
    category: "small-habit",
    icon: "🛍",
    iconLabel: "Shopping bag",
    title: "Carry a Cloth Bag",
    shortDescription: "Avoiding five plastic bags per week is small but repeatable.",
    monthlySavings: 0.2,
    whyItMatters: "Reduces dependence on single-use plastic bags.",
    howTo: [
      "Keep reusable bags in vehicles",
      "Carry foldable bags in backpacks",
    ],
    indiaContext: "Supports compliance with India's plastic reduction initiatives and municipal plastic restrictions.",
    sourceName: "MoEFCC Plastic Waste Management Rules",
    sourceUrl: "https://moef.gov.in",
  },
  {
    id: "bucket-bath",
    category: "small-habit",
    icon: "💧",
    iconLabel: "Water droplet",
    title: "Use Bucket Instead of Shower",
    shortDescription: "Cuts hot water energy and water use together.",
    monthlySavings: 0.8,
    whyItMatters: "Reduces both water use and water-heating energy.",
    howTo: [
      "Use a bucket for daily bathing",
      "Reduce geyser runtime",
    ],
    indiaContext: "Many Indian households rely on electric geysers or LPG water heating.",
    sourceName: "Ministry of Jal Shakti",
    sourceUrl: "https://jalshakti-dowr.gov.in",
  },

  // ── BIG IMPACT ──
  {
    id: "non-veg-swap",
    category: "big-impact",
    icon: "🌱",
    iconLabel: "Seedling",
    title: "Replace One Non-Veg Meal Per Day",
    shortDescription: "Keep the plate familiar with dal, chana, paneer, or soy swaps.",
    monthlySavings: 2.7,
    whyItMatters: "Animal-based foods generally create higher emissions than plant-based proteins.",
    howTo: [
      "Replace one daily meal with dal",
      "Use chana, soy, paneer, rajma, or lentils",
    ],
    indiaContext: "Works naturally within traditional Indian diets without requiring major lifestyle changes.",
    sourceName: "FAO Livestock and Environment",
    sourceUrl: "https://www.fao.org/livestock-environment",
  },
  {
    id: "rooftop-solar",
    category: "big-impact",
    icon: "☀",
    iconLabel: "Sun",
    title: "Explore PM Surya Ghar Rooftop Solar",
    shortDescription: "Estimated at 120 kgCO₂e saved per year for a small home system.",
    monthlySavings: 10.0,
    whyItMatters: "Solar electricity reduces dependence on grid-generated power.",
    howTo: [
      "Check roof suitability",
      "Review subsidy eligibility",
      "Apply through official portal",
    ],
    indiaContext: "PM Surya Ghar: Muft Bijli Yojana provides rooftop solar support for residential households.",
    sourceName: "PM Surya Ghar",
    sourceUrl: "https://pmsuryaghar.gov.in",
  },
  {
    id: "ev-two-wheeler",
    category: "big-impact",
    icon: "🛵",
    iconLabel: "Scooter",
    title: "Switch to Electric Two-Wheeler",
    shortDescription: "Best when your commute is predictable and charging is easy.",
    monthlySavings: 18.0,
    whyItMatters: "EVs typically produce lower lifecycle emissions and significantly lower operating costs.",
    howTo: [
      "Evaluate charging availability",
      "Compare EV scooter models",
      "Calculate monthly fuel savings",
    ],
    indiaContext: "PM E-DRIVE and related EV incentive programs support electric mobility adoption.",
    sourceName: "PM E-DRIVE Scheme",
    sourceUrl: "https://heavyindustries.gov.in/pm-e-drive-scheme",
  },
  {
    id: "rail-over-flight",
    category: "big-impact",
    icon: "🚄",
    iconLabel: "High-speed train",
    title: "Take Rail Instead of One Flight",
    shortDescription: "Indian Railways is a strong option for many short routes.",
    monthlySavings: 23.0,
    whyItMatters: "Rail travel generally produces much lower emissions per passenger-kilometre than aviation.",
    howTo: [
      "Choose rail for domestic trips under ~800 km where practical",
      "Compare travel time vs emissions",
    ],
    indiaContext: "Indian Railways is one of the world's largest rail networks and often provides a practical alternative to short-haul domestic flights.",
    sourceName: "Indian Railways",
    sourceUrl: "https://indianrailways.gov.in",
  },

  // ── INDIA-SPECIFIC ──
  {
    id: "lpg-leak-check",
    category: "india-specific",
    icon: "🔥",
    iconLabel: "Fire",
    title: "Pressure-Check LPG Leaks",
    shortDescription: "Small cooking-efficiency fixes are high-value in Indian homes.",
    monthlySavings: 1.2,
    whyItMatters: "Leaks waste fuel, increase costs, and create safety risks.",
    howTo: [
      "Conduct periodic soap-water leak checks",
      "Inspect regulators and hoses",
      "Follow distributor safety guidelines",
    ],
    indiaContext: "A highly relevant efficiency improvement for LPG-dependent households.",
    sourceName: "MyLPG",
    sourceUrl: "https://mylpg.in",
  },
  {
    id: "compost-flowers",
    category: "india-specific",
    icon: "♻",
    iconLabel: "Recycling",
    title: "Compost Flowers and Peels",
    shortDescription: "Great fit for households near local gardens and temple areas.",
    monthlySavings: 2.4,
    whyItMatters: "Organic waste in landfills generates methane.",
    howTo: [
      "Create a simple compost bin",
      "Add kitchen scraps and garden waste",
      "Use compost for plants",
    ],
    indiaContext: "Especially useful near temples, gardens, and households generating flower waste.",
    sourceName: "Swachh Bharat Mission",
    sourceUrl: "https://swachhbharatmission.gov.in",
  },
  {
    id: "air-dry-clothes",
    category: "india-specific",
    icon: "👕",
    iconLabel: "T-shirt",
    title: "Air-Dry Clothes",
    shortDescription: "Useful through long dry spells and sunny balconies.",
    monthlySavings: 3.6,
    whyItMatters: "Eliminates electricity consumption from electric dryers.",
    howTo: [
      "Use balconies, rooftops, or drying racks",
      "Dry clothes during daylight hours",
    ],
    indiaContext: "India's climate and long sunny periods make air drying practical throughout much of the year.",
    sourceName: "Bureau of Energy Efficiency",
    sourceUrl: "https://beeindia.gov.in",
  },

  // ── ADDITIONAL SMALL HABIT ──
  {
    id: "led-bulbs",
    category: "small-habit",
    icon: "💡",
    iconLabel: "Light bulb",
    title: "Switch to LED Bulbs at Home",
    shortDescription: "Replace all incandescent and CFL bulbs with LEDs for instant energy savings.",
    monthlySavings: 4.2,
    whyItMatters: "LED bulbs use up to 80% less energy than incandescent bulbs and last 15–25 times longer, reducing both electricity consumption and waste.",
    howTo: [
      "Audit all light fixtures in your home",
      "Replace incandescent and CFL bulbs with BEE 5-star rated LEDs",
      "Use lower wattage LEDs in areas that don't need bright light",
      "Turn off lights when leaving a room",
    ],
    indiaContext: "The UJALA scheme has distributed over 36 crore LED bulbs across India at subsidized prices, making the switch affordable for most households.",
    sourceName: "UJALA Scheme — EESL",
    sourceUrl: "https://www.eeslindia.org/en/UJALA",
  },
  {
    id: "carpool-commute",
    category: "small-habit",
    icon: "🚗",
    iconLabel: "Car",
    title: "Carpool to Work 3x/Week",
    shortDescription: "Share rides with colleagues or neighbors to cut per-person emissions in half.",
    monthlySavings: 6.8,
    whyItMatters: "A car carrying 3 passengers instead of 1 reduces per-person transport emissions by roughly 65%. Carpooling also reduces traffic congestion and road wear.",
    howTo: [
      "Coordinate with 2–3 colleagues living nearby",
      "Use carpooling apps like Quick Ride or BlaBlaCar",
      "Alternate driving duties weekly",
      "Share fuel costs to make it financially attractive",
    ],
    indiaContext: "Major Indian cities like Bengaluru, Hyderabad, and Delhi have active carpooling communities. Apps like Quick Ride are popular for office commutes.",
    sourceName: "Ministry of Road Transport & Highways",
    sourceUrl: "https://morth.nic.in",
  },
  {
    id: "unplug-standby",
    category: "small-habit",
    icon: "🔌",
    iconLabel: "Electric plug",
    title: "Unplug Devices on Standby",
    shortDescription: "Phantom loads from idle chargers and appliances waste 5–10% of household electricity.",
    monthlySavings: 1.5,
    whyItMatters: "Standby power consumption (phantom load) accounts for 5–10% of residential electricity use globally. Unplugging eliminates this invisible waste.",
    howTo: [
      "Use power strips with on/off switches for entertainment centers",
      "Unplug phone and laptop chargers when not in use",
      "Turn off the geyser after use instead of leaving it on standby",
      "Switch off Wi-Fi routers at night if not needed",
    ],
    indiaContext: "With rising appliance ownership in Indian households, standby power waste has increased significantly. BEE recommends using power strips for easy management.",
    sourceName: "Bureau of Energy Efficiency",
    sourceUrl: "https://beeindia.gov.in",
  },
  {
    id: "plant-tree",
    category: "small-habit",
    icon: "🌳",
    iconLabel: "Tree",
    title: "Plant and Maintain One Tree",
    shortDescription: "A single mature tree absorbs approximately 22 kg of CO₂ per year.",
    monthlySavings: 1.8,
    whyItMatters: "Trees are natural carbon sinks that absorb CO₂ during photosynthesis, improve air quality, reduce urban heat islands, and support biodiversity.",
    howTo: [
      "Choose native species suited to your local climate",
      "Plant in your garden, balcony (potted), or community spaces",
      "Water regularly during the first 2 years",
      "Join local tree-planting drives for community impact",
    ],
    indiaContext: "India's Green India Mission targets 5 million hectares of additional forest cover. Local nurseries and NGOs like SankalpTaru facilitate urban tree planting.",
    sourceName: "Green India Mission — MoEFCC",
    sourceUrl: "https://moef.gov.in/en/division/forest-divisions/green-india-mission",
  },
  {
    id: "refill-bottle",
    category: "small-habit",
    icon: "🧴",
    iconLabel: "Bottle",
    title: "Carry a Refillable Water Bottle",
    shortDescription: "Eliminating 2 plastic bottles daily prevents ~60 bottles/month from waste streams.",
    monthlySavings: 0.5,
    whyItMatters: "Producing a single PET bottle generates about 82g of CO₂. Manufacturing, filling, and transporting bottled water has a significantly higher carbon footprint than tap or filtered water.",
    howTo: [
      "Invest in a quality stainless steel or copper bottle",
      "Install a water purifier at home and office",
      "Refill at railway station water ATMs (Jal Jeevan)",
      "Keep a bottle in your bag as a daily habit",
    ],
    indiaContext: "India generates over 9,400 tonnes of plastic waste daily. Railway stations have introduced water vending machines under the Jal Jeevan Mission to reduce plastic bottle use.",
    sourceName: "Jal Jeevan Mission",
    sourceUrl: "https://jaljeevanmission.gov.in",
  },

  // ── ADDITIONAL BIG IMPACT ──
  {
    id: "home-insulation",
    category: "big-impact",
    icon: "🏠",
    iconLabel: "House",
    title: "Insulate Your Home Properly",
    shortDescription: "Reduce AC and heater usage by 30–40% with basic wall and roof insulation.",
    monthlySavings: 12.5,
    whyItMatters: "Heating and cooling account for 40–60% of a home's energy use. Proper insulation dramatically reduces the energy needed to maintain comfortable temperatures.",
    howTo: [
      "Apply reflective coatings or cool roof paint to your rooftop",
      "Use double-glazed or tinted windows",
      "Install thermal curtains or blinds",
      "Seal gaps around doors and windows with weather stripping",
    ],
    indiaContext: "ECBC (Energy Conservation Building Code) encourages thermal insulation in residential buildings. Cool roof coatings are especially effective in hot Indian climates.",
    sourceName: "Energy Conservation Building Code — BEE",
    sourceUrl: "https://beeindia.gov.in/en/ecbc",
  },
  {
    id: "rainwater-harvest",
    category: "big-impact",
    icon: "🌧",
    iconLabel: "Rain cloud",
    title: "Install Rainwater Harvesting",
    shortDescription: "Capture monsoon rain to reduce dependence on energy-intensive municipal water supply.",
    monthlySavings: 5.2,
    whyItMatters: "Municipal water treatment and pumping is energy-intensive. Rainwater harvesting reduces demand on these systems while recharging local groundwater.",
    howTo: [
      "Set up rooftop collection connected to a storage tank",
      "Install a basic filtration system for household use",
      "Use collected water for gardening and non-drinking purposes",
      "Check municipal incentives and mandatory requirements",
    ],
    indiaContext: "Rainwater harvesting is mandatory in several Indian cities including Chennai, Bengaluru, and Delhi. Many states offer subsidies and tax rebates for installation.",
    sourceName: "Central Ground Water Board",
    sourceUrl: "https://cgwb.gov.in",
  },
  {
    id: "wfh-hybrid",
    category: "big-impact",
    icon: "💻",
    iconLabel: "Laptop",
    title: "Work From Home 2 Days/Week",
    shortDescription: "Eliminating 2 commute days weekly saves fuel, reduces traffic, and cuts emissions.",
    monthlySavings: 15.0,
    whyItMatters: "Daily commuting is one of the largest individual carbon contributors. Even 2 days of remote work per week can reduce commute emissions by 40%.",
    howTo: [
      "Negotiate a hybrid work arrangement with your employer",
      "Set up an energy-efficient home office",
      "Batch in-person meetings on office days",
      "Use video conferencing for routine meetings",
    ],
    indiaContext: "Post-pandemic, many Indian IT companies and startups have adopted hybrid work policies. This is especially impactful in traffic-heavy cities like Bengaluru and Mumbai.",
    sourceName: "NITI Aayog — Future of Work",
    sourceUrl: "https://niti.gov.in",
  },
  {
    id: "organic-local-food",
    category: "big-impact",
    icon: "🥬",
    iconLabel: "Leafy green",
    title: "Buy Local & Seasonal Produce",
    shortDescription: "Locally sourced seasonal food travels less and requires fewer cold-chain resources.",
    monthlySavings: 4.5,
    whyItMatters: "Food transportation accounts for 6–10% of food-related emissions. Imported and out-of-season produce requires refrigerated transport and storage, multiplying its carbon footprint.",
    howTo: [
      "Shop at local sabzi mandis and farmer markets",
      "Choose seasonal fruits and vegetables",
      "Join a Community Supported Agriculture (CSA) group",
      "Grow herbs and microgreens at home",
    ],
    indiaContext: "India has a rich tradition of seasonal eating. Mandis and local farmer markets are widespread, making local sourcing practical and affordable.",
    sourceName: "National Agricultural Market (eNAM)",
    sourceUrl: "https://enam.gov.in",
  },

  // ── ADDITIONAL INDIA-SPECIFIC ──
  {
    id: "solar-water-heater",
    category: "india-specific",
    icon: "🌡",
    iconLabel: "Thermometer",
    title: "Install a Solar Water Heater",
    shortDescription: "Replace electric geysers with solar thermal systems for hot water needs.",
    monthlySavings: 7.5,
    whyItMatters: "Water heating accounts for a significant portion of household energy use. Solar water heaters can provide 60–80% of a home's hot water needs with zero operating emissions.",
    howTo: [
      "Assess roof space and sun exposure",
      "Choose between flat plate and evacuated tube collectors",
      "Apply for MNRE subsidies through your state nodal agency",
      "Connect as a pre-heater to your existing geyser as backup",
    ],
    indiaContext: "MNRE provides subsidies of up to ₹6,000 per system. Several states mandate solar water heaters for new buildings above a certain size.",
    sourceName: "Ministry of New & Renewable Energy",
    sourceUrl: "https://mnre.gov.in",
  },
  {
    id: "biogas-cooking",
    category: "india-specific",
    icon: "🐄",
    iconLabel: "Cow",
    title: "Set Up a Small Biogas Plant",
    shortDescription: "Convert kitchen and cattle waste into cooking gas and organic fertilizer.",
    monthlySavings: 8.0,
    whyItMatters: "Biogas captures methane from organic waste that would otherwise escape into the atmosphere. It replaces LPG/firewood for cooking and produces nutrient-rich slurry for farming.",
    howTo: [
      "Assess daily organic waste availability (min 25 kg/day ideal)",
      "Choose a compact 1–2 cubic meter model for households",
      "Apply for subsidy under the National Biogas Programme",
      "Use the slurry output as organic fertilizer",
    ],
    indiaContext: "The MNRE National Biogas and Manure Management Programme supports rural and semi-urban households. Prefabricated portable biogas units are now available for urban homes.",
    sourceName: "National Biogas Programme — MNRE",
    sourceUrl: "https://mnre.gov.in/bio-energy/current-status",
  },
  {
    id: "cycle-to-work",
    category: "india-specific",
    icon: "🚲",
    iconLabel: "Bicycle",
    title: "Cycle for Short Trips Under 5 km",
    shortDescription: "Replace auto-rickshaw or scooter trips with cycling for errands and short commutes.",
    monthlySavings: 3.8,
    whyItMatters: "Short motorized trips are disproportionately polluting because engines are least efficient during cold starts and short distances. Cycling produces zero emissions.",
    howTo: [
      "Use a bicycle for trips under 5 km",
      "Explore public bike-sharing systems in your city",
      "Plan safe cycling routes using Google Maps cycling mode",
      "Keep a lock and basic repair kit handy",
    ],
    indiaContext: "Cities like Bhopal, Mysuru, Chandigarh, and Pune have launched public bicycle-sharing schemes. Many cities are building dedicated cycling infrastructure under Smart Cities Mission.",
    sourceName: "Smart Cities Mission",
    sourceUrl: "https://smartcities.gov.in",
  },
  {
    id: "ujjwala-clean-cooking",
    category: "india-specific",
    icon: "🍳",
    iconLabel: "Cooking pan",
    title: "Switch from Firewood to Clean Cooking",
    shortDescription: "Transitioning from biomass chulhas to LPG or induction reduces indoor and outdoor emissions.",
    monthlySavings: 9.0,
    whyItMatters: "Traditional biomass cookstoves have very low efficiency (10–15%) and emit harmful particulate matter, black carbon, and methane. Clean cooking fuel reduces all of these.",
    howTo: [
      "Check eligibility for Pradhan Mantri Ujjwala Yojana",
      "Apply for a free LPG connection through your nearest distributor",
      "Consider induction cooktops as an electric alternative",
      "Ensure proper ventilation in your kitchen",
    ],
    indiaContext: "PM Ujjwala Yojana has provided over 9.6 crore free LPG connections to BPL households, making the transition to clean cooking fuel accessible across rural India.",
    sourceName: "Pradhan Mantri Ujjwala Yojana",
    sourceUrl: "https://www.pmuy.gov.in",
  },
  {
    id: "digital-payments",
    category: "india-specific",
    icon: "📱",
    iconLabel: "Mobile phone",
    title: "Go Paperless with Digital Payments",
    shortDescription: "Use UPI, e-bills, and digital receipts to reduce paper consumption and trips to banks.",
    monthlySavings: 0.4,
    whyItMatters: "Paper production is resource-intensive, requiring trees, water, and energy. Digital transactions also reduce the need for physical travel to banks and payment centers.",
    howTo: [
      "Switch to UPI apps for daily transactions",
      "Opt for e-statements from banks and utilities",
      "Use digital receipts instead of printed ones",
      "Pay bills online through BBPS",
    ],
    indiaContext: "India's UPI processed over 13 billion transactions monthly in 2024, making it the world's largest real-time payment system. The Digital India initiative promotes paperless governance.",
    sourceName: "Digital India Programme",
    sourceUrl: "https://digitalindia.gov.in",
  },
];
